class ManageKeywords:
    keywords_dictionary = {
        "Login": ["username", "password", "login", "sign in", "remember me", "log in", "forgot password", "reset password", "welcome back",
                  "authenticate", "secure login", "user credentials", "account access", "register", "verify", "two-factor authentication", "biometric authentication"],
        "Setting": ["setting", "account", "preferences", "Accessibility", "user preferences", "customize settings", "personalization",
                    "configuration", "privacy settings", "notification preferences", "language settings", "theme selection", "options", "account security"],
        "Profile": ["name", "photo", "about", "age", "profile", "wishlist", "user profile picture", "personal information", "picture", "interests", "profile settings", "activity history", "social links", "profile privacy"],
        "Splash": ["splash", "app name", "logo", "loading", "splash screen", "branding", "initial loading", "loading animation", "brand recognition", "app launch", "first impression"],
        "Mail": ["mail", "email", "subject", "inbox", "sent", "drafts", "trash", "compose", "reply", "forward", "delete", "search", "attachments", "spam folder", "email composition"],
        "Browser": ["browser", "web", "internet", "search", "URL", "address bar", "back", "forward", "reload", "stop", "bookmark", "history", "share", "navigate websites", "browser extensions", "bookmark websites", "browsing history"],
        "Home": ["home", "dashboard", "main", "menu", "homepage", "overview", "sliders", "toolbar", "featured content", "overview panels", "toolbar settings", "dashboard widgets", "main screen layout", "quick access", "home screen design", "content sliders"],
        "Search": ["search", "query", "results", "filter", "sorting", "suggestions", "history", "popularity", "relevance",
                   "advanced search", "refine results", "filter options", "search suggestions", "search history",
                   "popularity ranking", "search algorithms", "relevance filters", "search by category", "search by date",
                   "search by keyword"],
        "Chat": ["chat", "Send photo", "write your comment", "send message", "subject", "conversation", "message content",
                 "type a message", "your message",
                 "contacts", "ContactsHolder", "groups", "composing", "send a message", "send a comment", "receive", "attachments",
                 "messaging app",
                 "conversations list", "group chats", "message notifications", "contact management", "message threading",
                 "attachment sharing",
                 "message archives", "message search", "message encryption", "emoticons and stickers"],
        "List": ["list", "menu", "detail", "select", "search", "sorting", "items", "edit entries", "delete items", "list sorting",
                 "filter options", "list search", "list management", "item categories", "item descriptions"],
        "Alert": ["alert", "notification", "reminder", "warning", "dialog", "prompt", "action", "close", "warning alerts",
                  "dialog boxes"],
        "Welcome": ["welcome", "introduction", "overview", "features", "splash", "sign up", "explore features", "join our community",
                    "tour the app"],
        "Menu": ["Home", "list", "Profile", "Settings", "Help", "Contact", "About", "Privacy Policy", "Terms of Service", "logout",
                 "my account", "my orders", "my favorites", "my wishlist", "notifications", "messages", "chat", "search", "categories",
                 "featured products", "new products", "best sellers", "sales", "discounts", "coupons", "cart", "checkout", "shipping",
                 "payment", "order confirmation", "track order", "return order", "customer support", "feedback", "share"],
        "Map": ["map", "location", "GPS", "navigation", "directions", "search", "points of interest", "route", "traffic",
                "satellite", "street view", "explore nearby", "map settings", "map layers", "find your way", "map routes"]
    }